/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Tuliva.AnimalKingdom.Clients;
import static com.Tuliva.AnimalKingdom.Runtime.MainProgram.ClearScreen;
import static com.Tuliva.AnimalKingdom.Runtime.MainProgram.DisplayMenu;
import com.Tuliva.AnimalKingdom.Utilities.Utilities;
import javax.swing.ImageIcon;

/**
 *
 * @author student
 */
public class FormClient extends javax.swing.JFrame {

    /**
     * Creates new form FormClient
     */
    
    private String _firstName;
    private String _lastName;
    private String _password;
    public FormClient() {
        initComponents();
        lstAnimal.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnSubmit = new javax.swing.JButton();
        lblAnimalToCreate = new javax.swing.JLabel();
        lstAnimalToCreate = new javax.swing.JScrollPane();
        lstAnimal = new javax.swing.JList<>();
        btnExit = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblAnimalKingdom = new javax.swing.JLabel();
        lblAnimal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 255, 51));

        lblFirstName.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        lblFirstName.setText("Enter Your First Name:");

        lblLastName.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        lblLastName.setText("Enter Your Last Name:");

        lblPassword.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        lblPassword.setText("Enter Your Password:");

        txtFirstName.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N

        txtLastName.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N

        txtPassword.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N

        btnSubmit.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnSubmit.setText("Log In");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblAnimalToCreate.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        lblAnimalToCreate.setText("Click the Animal to Create:");

        lstAnimal.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lstAnimal.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Duck", "Trout", "Human" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstAnimal.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstAnimalValueChanged(evt);
            }
        });
        lstAnimalToCreate.setViewportView(lstAnimal);

        btnExit.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblTitle.setText("Login Information");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFirstName)
                            .addComponent(lblLastName)
                            .addComponent(lblPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFirstName)
                            .addComponent(txtLastName)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAnimalToCreate)
                        .addGap(18, 18, 18)
                        .addComponent(lstAnimalToCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitle)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAnimalToCreate)
                    .addComponent(lstAnimalToCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblAnimalKingdom.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lblAnimalKingdom.setText("Welcome to the Animal Kingdom!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAnimal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(lblAnimalKingdom)
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAnimalKingdom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnimal))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        this._firstName = txtFirstName.getText();
        this._lastName = txtLastName.getText();
        //logging what the user entered
        Utilities.LogIt("The user entered for last name:" + _lastName +
            "\nThe user entered for first name: " + _firstName + "\n" +
            "The password is classified.\n",
            Utilities.MessageSeverity.INFORMATIONAL, true);
        
        txtFirstName.setEnabled(false);
        txtLastName.setEnabled(false);
        txtPassword.setEnabled(false);
        btnSubmit.setEnabled(false);
        
        lstAnimal.setEnabled(true);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
        //clearing the screen with a method that was created
        ClearScreen();
        DisplayMenu();
    }//GEN-LAST:event_btnExitActionPerformed

    private void lstAnimalValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstAnimalValueChanged
        switch (this.lstAnimal.getSelectedIndex()){
            case 0:
                lblAnimal.setIcon(new ImageIcon("Resources/daffyduck.jpg"));
                Utilities.LogIt("FormClient::The user chose a duck in the list box.\n",
                    Utilities.MessageSeverity.INFORMATIONAL, true);
                    break;
            case 1:
                lblAnimal.setIcon(new ImageIcon("Resources/trout.png"));
                Utilities.LogIt("FormClient::The user chose a trout in the list box.\n",
                    Utilities.MessageSeverity.INFORMATIONAL, true);
                    break;
            case 2:
                lblAnimal.setIcon(new ImageIcon("Resources/Human.jpg"));
                Utilities.LogIt("FormClient::The user chose a human in the list box.\n",
                    Utilities.MessageSeverity.INFORMATIONAL, true);
                    break;
            default:
                break;
        }
    }//GEN-LAST:event_lstAnimalValueChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
        //clearing the screen with a method that was created
        ClearScreen();
        DisplayMenu();
    }//GEN-LAST:event_formWindowClosing
     
    
    /**
     * @param args the command line arguments
     */
    public static void FormMain(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAnimal;
    private javax.swing.JLabel lblAnimalKingdom;
    private javax.swing.JLabel lblAnimalToCreate;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList<String> lstAnimal;
    private javax.swing.JScrollPane lstAnimalToCreate;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
